### PR TITLE
feat: :sparkles: add simple substitution cipher and update README accordingly

### LINKED ISSUE #3: Implement a Simple Substitution Cipher
Conceptually very similar to an XOR cipher (XOR is a type of simple substitution cipher).

Simple substitution ciphers usually replace each character with another predefined character.

There are more complex versions like Homophonic Substitution Ciphers, Polygraphic Substitution Ciphers, etc; but for this issue a simple version should be okay.

More details about the specifics of Substitution cipher can be found on [Wikipedia](https://en.wikipedia.org/wiki/Substitution_cipher)

The implementation should stylistically match the existing code (XOR, for example).

### PR DESCRIPTION
**Pull request by inclinedadarsh**
Fixes #3 

## Changes made:
- Added `simple-substitution` cipher in the package
- Add all other _chore_ files for the package to work
- Added `simple-substitution.spec.ts` file for testing
- Updated the `README.md` file with the new cipher documentation

## Breaking Changes
No breaking changes

### CODE REVIEW

**Review by fa7ad — COMMENTED** [review]
Looks good to me! I'll merge the PR later, but add the label so you can get this approved for hacktoberfest.

Thanks for your contribution.

**Comment by fa7ad** [comment]
Hey @inclinedadarsh did you write the tests by hand because I can't seem to get any of them to pass successfully. I don't want to jump to conclusions, but I suspect the tests were generated by an LLM or copied blindly from the other test suites. For now, I'm removing the accepted label. 

image

**Comment by inclinedadarsh** [comment]
Heyy @fa7ad 
Actually I'm pretty new to TypeScript and have never written a testing file.
All I was trying with this file was to copy the structure of the `.spec.ts` file of Caesar Cipher and implement it here.

I can try to fix that.
Can you help me with it?

What exactly did go wrong and how do I correct it?

**Comment by fa7ad** [comment]
Okay, it's good to get some context and I apologize for assuming LLM (I've had to review some spammy PRs generated by LLMs on a few other OSS projects this year).

There's a few things that you might want to do:

1. The formatting isn't quite consistent with the rest of the project. This is easy to solve since the project uses prettier, so you just need to run `yarn nx format`.
2. Next, your branch is no longer in sync with the current `main` branch. You can pull-in the changes with a git rebase (or merge, if that's what you prefer).
3. The tests, you got the format right but the tests should match expected outputs. A easy way might be to test against a reference implementation of the cipher. I initially thought the tests were wrong, but this might be a case of bad implementation instead of bad tests.

For example,

The test here (Line 9 of spec.ts file) seems to be failing, the expected output `IFMMP` is not being produced by the function. I tested against a reference implementation [here](https://cryptii.com/pipes/alphabetical-substitution), `IFMMP` should be the expected output but the test runner seems to report that the function is returning `HELLO`. I'm guessing this is because the implementation only works for lowercase `a` to `z`.

image


You can run the test suite using `yarn nx test simple-substitution`. If everything goes well you shouldn't see any red output.

**Comment by inclinedadarsh** [comment]
Heyy @fa7ad 
I have made some changes in the `simple-subsitution.ts` file and you were correct, it was about bad implementation of the cipher and not the test cases.

I add _work around_ for capital letters. Other than that, for some reason I thought the decode function would work like that, but after testing it didn't, so I rewrote the function and now it works.

Actually I pushed the earlier code without really testing as I didn't know how to do that. I should have asked you though.
Now I have made some changes and have also formatted the code.
Have a look at them and let me know if you need any more changes.

**Pull request merged**
